[package]
name = "bevy_stl"
version = "0.3.0"
authors = ["Niklas Cathor <niklas.cathor@gmx.de>"]
edition = "2018"
license = "MIT"
description = "STL loader for bevy, based on stl_io"
repository = "https://github.com/nilclass/bevy_stl"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_app = "0.5"
bevy_asset = "0.5"
bevy_render = "0.5"
bevy_utils = "0.5"
anyhow = "1.0"
thiserror = "1.0"
stl_io = "0.5.2"

[dev-dependencies]
bevy = { version = "0.5", default-features = false, features = [
    "render",
    "bevy_wgpu",
    "bevy_winit",
    "bevy_gltf",
    "x11",
] }

[features]
default = []

# Along with the triangle mesh, generate an additional wireframe mesh (a PrimitiveTopology::LineList).
# The wireframe mesh can be accessed by `asset_server.load("my-model.stl#wireframe")`.
wireframe = []

[[example]]
name = "spinning_disc"
path = "examples/spinning_disc.rs"
