name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Build example
      run: cargo build --verbose --example spinning_disc
    - name: Build (wireframe feature)
      run: cargo build --verbose --features wireframe
    - name: Build example (wireframe feature)
      run: cargo build --verbose --example spinning_disc_wireframe --features wireframe
